### ISSUE TITLE
自定义仓库有哪些要求

### ISSUE THREAD

**Issue by BombLing** [TencentBlueKing/ci-uploadArtifact#4]
将构建机上的文件归档或自定义仓库: 是自己安装的蓝盾仓库吗？https://github.com/ci-plugins/bk-repo.git

**Comment by irwinsun** [comment]
可以根据安装情况决定,  bk-ci 配置 BK_CI_ARTIFACTORY_REALM
https://github.com/TencentBlueKing/bk-ci/blob/master/scripts/bkenv.properties#L284C9-L284C9
